// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2fIwInj0aLT9GdVNbo7WmxeqifYKF7mk',
    appId: '1:527788671289:web:d858a152d4a6597b23a8e8',
    messagingSenderId: '527788671289',
    projectId: 'ridhun-s-project',
    authDomain: 'ridhun-s-project.firebaseapp.com',
    databaseURL: 'https://ridhun-s-project-default-rtdb.firebaseio.com',
    storageBucket: 'ridhun-s-project.appspot.com',
    measurementId: 'G-01F8QE7DZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQiJ_HoKN8GzZrrUZfT55sJFYEQ7Iqjcs',
    appId: '1:527788671289:android:71661e6de60cef1f23a8e8',
    messagingSenderId: '527788671289',
    projectId: 'ridhun-s-project',
    databaseURL: 'https://ridhun-s-project-default-rtdb.firebaseio.com',
    storageBucket: 'ridhun-s-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArdjbKzc5ZQJaUdGOIJa9ax2juXEwH7ZU',
    appId: '1:527788671289:ios:a77778c756b4355423a8e8',
    messagingSenderId: '527788671289',
    projectId: 'ridhun-s-project',
    databaseURL: 'https://ridhun-s-project-default-rtdb.firebaseio.com',
    storageBucket: 'ridhun-s-project.appspot.com',
    androidClientId: '527788671289-8t0dn4sk0fh21ndhab13806epjr7fmp6.apps.googleusercontent.com',
    iosClientId: '527788671289-aqnsi6l89ic32utbb6o5888vtmj1rt2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.irohubProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArdjbKzc5ZQJaUdGOIJa9ax2juXEwH7ZU',
    appId: '1:527788671289:ios:19581c2fb68c5d4823a8e8',
    messagingSenderId: '527788671289',
    projectId: 'ridhun-s-project',
    databaseURL: 'https://ridhun-s-project-default-rtdb.firebaseio.com',
    storageBucket: 'ridhun-s-project.appspot.com',
    androidClientId: '527788671289-8t0dn4sk0fh21ndhab13806epjr7fmp6.apps.googleusercontent.com',
    iosClientId: '527788671289-tmu8noi231phr9eug57tffbk3k73oqp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.irohubProject.RunnerTests',
  );
}
